#!/bin/bash

echo "Current dir : ${pwd}"
#xvlog -sv -f ./verilog_filelist.f
xvlog -sv ./tb_AXI_Clock_Converter.sv ./axi_clock_converter_0_sim_netlist.v
xelab tb_axi_clock_converter -debug all -s tb_axi_clock_converter
xsim tb_axi_clock_converter -gui -wdb Xilinx_axi_clock_converter.wdb
